### ISSUE TITLE
Produire des pré-compilés "exécutables natifs" du traducteur "touistl.native" et adapter à windows

### ISSUE THREAD

**Issue by maelvalais** [FredMaris/touist#5]
- Win7 32 bits, 
- Win7 64 bits, 
- MacOSX 64 bits (intel)
- Linux 32 bits
- Linux 64 bits

**Comment by maelvalais** [comment]
@olzd Il faudrait fournir à Skander une version windows7/64bits pour qu'il puisse enfin tester tout ça

**Comment by maelvalais** [comment]
J'ai vu que `fileutils` était compatible `win32` : http://le-gall.net/sylvain+violaine/ocaml-fileutils.html

**Comment by olzd** [comment]
Pour `opam` c'est de la cross-compilation vers windows visiblement. Idéalement il faudrait pouvoir compiler depuis windows directement.

**Comment by maelvalais** [comment]
Ah oui, en effet ^^ Je confonds un peu "cross-compilation" et compilation directement depuis la machine hôte...

**Comment by maelvalais** [comment]
J'ai vu que tu as downgradé la version nécessaire pour ocaml dans 0782ba7218dd168029db0588790ced75c8e87ff4. Du coup, y'a plus besoin que de ocaml 4.01.1, on va peut-être arriver à mettre ça sous windows :p

**Comment by olzd** [comment]
Faut voir. Je sais pas comment installer `menhir` et `fileutils` sous windows.

**Comment by maelvalais** [comment]
Mis à part utiliser Cygwin sous windows, je n'ai pas réussi à trouver le moyen de faire ça. Ou sinon d'utiliser de la cross-compilation vers du natif windows avec du `x86_64-w64-mingw32-gcc`, `x86_64-w64-mingw32-menhir` et `x86_64-w64-mingw32-ocaml`, etc. Mais je n'ai réussi qu'à installer `x86_64-w64-mingw32-gcc` après 4h de galères...

**Comment by maelvalais** [comment]
J'ai finalement réussi à installer un cross-compileur`x86_64-w64-mingw32-ocaml`. Pour les librairies :
- j'ai bien `menhir`
- j'ai pas `fileutils` par contre...
Galère...

**Comment by maelvalais** [comment]
Voilà, ma première cross-compilation d'ocaml vers i686 :p 
![capture](https://cloud.githubusercontent.com/assets/2195781/6693588/4e6de180-ccd4-11e4-9d28-2ca602f8cf88.PNG)

**Comment by maelvalais** [comment]
Cooool j'ai enfin produit un exécutable windows :p 
C'est compilé pour du windows 32 bits, mais ça marche aussi sur les 64 bits.
Voilà, tu pourras enfin tester @Aleksandair :)
https://drive.google.com/file/d/0B5mz8k-t6PT0S1QyTi0tWHJhSFk/view?usp=sharing

**Comment by maelvalais** [comment]
Bon ben c'est bon, problème résolu pour win32 du moins.

**Comment by maelvalais** [comment]
Bon, je viens de réessayer d'installer `wodi`. Le mec qui tenait le site a apparemment enlevé tous les liens. Mais même en téléchargeant d'ailleurs, le dépôt qui contenait tous les packages n'est plus joignable… 
Seuls `opam` et `wodi` permettent d'installer `fileutils` et `menhir`. Du coup, on est coincés pour le moment ! 
@Aleksandair je me souviens, nous avions installé `wodi` sur ton laptop. As tu toujours cette installation ?

**Comment by maelvalais** [comment]
J'ai passé 8 à 10 heures sur ce problème… Qui en est maintenant un !
Il y a deux mois, j'avais trouvé `wodi` qui permettait d'installer proprement `fileutils` et `menhir`.
Mais depuis quelques jours, impossible de re-télécharger l'installeur (et les serveurs qui hébergeaient les packages ne répond plus).
Donc j'ai essayé : 
- de cross-compiler sur mon mac → j'y arrive pas
- de compiler sur Windows7 en utilisant `godi` directement → les serveurs ne répondent plus
- de compiler sur Windows7 en recompilant `menhir` et `fileutils` → j'y suis pas arrivé
- de cross-compiler depuis linux avec `i686-w64-mingw32-ocaml` (en utilisant le repo OPAM de [là](https://github.com/vouillon/opam-windows-repository)) → c'est la solution qui semble la plus prometteuse, mais il y a encore le souci de `fileutils`… 

Donc pour le moment, c'est le statu-quo. Je ne sais pas si nous arriverons un jour à recompiler sous Windows !

**Comment by maelvalais** [comment]
Je suis retourné sur le site de wodi aujourd'hui. Ils ont carrément fermé le site entier. Comme expliqué plus haut, wodi était un gestionnaire de paquets. Il n'en existe que deux pour ocaml : OPAM et wodi.

Les seuls choix restants sont : 
- ou bien on compile à la main `fileutils` et `menhir` en installant ocaml via mingw/cygwin
- ou bien on trouve une façon d'installer OPAM sous windows via mingw/cygwin

Dur dur...

**Comment by olzd** [comment]
On pourrait éventuellement se passer de `fileutils`. Faudrait réécrire les fonctions utilitaires et tout. Par contre pour `menhir` ce serait plus embêtant.

**Comment by maelvalais** [comment]
Bonne nouvelle, j'ai remis le SSD qui était HS ; j'ai réussi à booter sur Windows 7 et à récupérer `wodi`. Du coup, voilà l'archive qui contient tout ce dont on a besoin : https://dl.dropboxusercontent.com/u/41771140/wodi32.zip
À l'intérieur, il y a
- ocaml 4.02.1
- fileutils
- menhir
- et même oasis
Donc on peut release pour windows !

J'ai crée une VM avec Windows 7 pour compiler. Je fais encore quelques tests et je fournis une release Mac/Windows/Linux (j'ai aussi créé une VM Ubuntu pour ça).

**Comment by oGasquet** [comment]
Le 30/05/2015 12:09, Maël Valais a écrit :
>
> Bonne nouvelle, j'ai remis le SSD qui était HS ; j'ai réussi à booter 
> sur Windows 7 et à récupérer |wodi|. Du coup, voilà l'archive qui 
> contient tout ce dont on a besoin : 
> https://dl.dropboxusercontent.com/u/41771140/wodi32.zip
> À l'intérieur, il y a
>
>   * ocaml 4.02.1
>   * fileutils
>   * menhir
>   * et même oasis Donc on peut release pour windows !
>
> J'ai crée une VM avec Windows 7 pour compiler. Je fais encore quelques 
> tests et je fournis une release Mac/Windows/Linux (j'ai aussi créé une 
> VM Ubuntu pour ça).
>

ok super, j'attends ça !

**Comment by maelvalais** [comment]
Voilà, c'est fait. `touistc-win-v0.32-33-g1a310d9` est [disponible sur le drive](https://drive.google.com/folderview?id=0B5mz8k-t6PT0cW5FSTBxNmgxUjQ&usp=sharing).

**Comment by maelvalais** [comment]
Problème enfin résolu avec l'ajout d'AppVeyor dans la v1.1.1 (c8b025da30). J'utilise le snapshot de wodi32 au dessus. Du coup, AppVeyor va, comme travis-ci pour linux/mac : 
- (spécifique à AppVeyor) télécharger le wodi32.zip pour pouvoir avoir fileutils, menhir, oasis, ocaml
- ensuite, si le build passe et qu'on est sur un tag sur master, il va pousser le `.zip` sur la [release correspondante](https://github.com/FredMaris/touist/releases). 

La version v1.1.1 a donc un exécutable windows ! Youhou !!!

**Comment by maelvalais** [comment]
Problème de nouveau résolu plus pérennement avec le [travail](http://fdopen.github.io/opam-repository-mingw/installation/) de *fdopen*.
