### ISSUE TITLE
Ajout de l'ajout des clauses en cours d'execution

### ISSUE THREAD

**Issue by aheba** [FredMaris/touist#93]
Les modifications se feront sur l'API Minisat.jar, cela consiste à ajouter la fonctionalité d'ajout de clause en cours d'exécution du solveur, et de limiter l'espace de recherche des modèles ainsi que leurs répétitions. (Voir explication MAIL)

**Comment by maelvalais** [comment]
Je suis un peu perdu avec cet issue. Je ne comprends pas vraiment ce qu'il était prévu de faire. Pour le moment, je ferme l'issue.
